version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        rider-updates:1:1,
        module-created:3:1,
        payment-done:3:1,
        material-data:3:1,
        course:3:1
    depends_on:
      - zookeeper

  payment:
    image: node:18
    container_name: payment
    working_dir: /app
    volumes:
      - ./Backend/payment:/app
    ports:
      - "4003:4003"
    command: npm run dev
    depends_on:
      - kafka
